### ISSUE TITLE
Properties instances can't set custom separator

### ISSUE THREAD

**Issue by dimaspivak** [translate/python-jproperties#5]
Would a PR that adds something like `self.separator` as an optional attribute be accepted? I'm looking to override the default ` = ` separator to be `=`, because the property file I'm loading doesn't have spaces around the equal sign (and I don't want to make properties changed by this module look inconsistent). This would let users specify their own preferred specifier when creating `Properties`, which would then be propagated across, for example, when updating items.

**Comment by jleclanche** [comment]
What's generating a properties file without spaces? It's been a while but I'm fairly certain some form of whitespace is required, otherwise the Java impl doesn't read it.

You won't be able to PR a `self.separator` attr though. That's only there for writing. See [here](https://github.com/translate/python-jproperties/blob/master/jproperties.py#L149).

**Comment by dimaspivak** [comment]
`log4j.properties` files don't put spaces around their equal signs ([here's one example](https://github.com/apache/hadoop/blob/trunk/hadoop-hdfs-project/hadoop-hdfs/src/test/resources/log4j.properties)). 

Yeah, I'd just want it for writing. Specifically, when updating an existing key of a `Properties` instance (i.e. using the `__setitem__`), the property being updated can only created with the `Property` class defaults. My change would essentially use such a `self.separator` attribute, if it exists.

**Comment by jleclanche** [comment]
In that case if you can fix the separator parser so it also parses without spaces that's great. A self.separator attribute would just make it unnecessarily complex.

**Comment by dimaspivak** [comment]
I think maybe I'm not being clear, sorry :). What I'm saying is that things in terms of parsing are actually working great (`jproperties` is doing great with reading these files), the issue is just that after parsing a properties file that looks like
```
A=B
C=D
E=F
```
and doing
```
p['A'] = 'b'
```
The file ends up looking like
```
A = b
C=D
E=F
```
I'm just suggesting allowing the separator type to be set when instantiating the `Properties` instance so that updating existing keys (or adding new ones) lets the file look consistent.

**Comment by jleclanche** [comment]
Oh, right.

I'm not too hot on that idea because in order for jproperties not to alter separator style when re-serializing a file, it holds a separator attribute *per property*.

You can set it directly with something like this before serializing: 

```py
for node in propfile.nodes:
    node.separator = "="
```

**Comment by dimaspivak** [comment]
I see what you mean. Hm... how about something that doesn't tie the separator style to a `Properties` instance but which lets users specify the separator without having to fork the repo? [Here's my stab at it](https://github.com/dimaspivak/python-jproperties/commit/eeaa93beaa6d4a09916bfc106ec562a44ec9d148), which lets a user set an environmental variable to override the default ` = `. If you're not interested in taking a PR, that's alright, but I figure I'm not the only one interested in this kind of use case and I'd love to contribute to thank you guys for the beautiful library you have here.

**Comment by jleclanche** [comment]
Yeah, I'd rather not mess about the env variables, that's super nasty :/

I added a `DEFAULT_SEPARATOR` attribute to property. You can monkeypatch that:

```py
from jproperties import Property

Property.DEFAULT_SEPARATOR = "="
```
